const mockDataFirstLetterS = {
  drinks: [
    {
      idDrink: '17141',
      strDrink: 'Smut',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Punch / Party Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Beer mug',
      strInstructions: 'Throw it all together and serve real cold.',
      strInstructionsES: null,
      strInstructionsDE: 'Schütte alles zusammen und serviere es kalt.',
      strInstructionsFR: null,
      strInstructionsIT: 'Metti tutto insieme e servi freddo.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rx8k8e1504365812.jpg',
      strIngredient1: 'Red wine',
      strIngredient2: 'Peach schnapps',
      strIngredient3: 'Pepsi Cola',
      strIngredient4: 'Orange juice',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/3 part ',
      strMeasure2: '1 shot ',
      strMeasure3: '1/3 part ',
      strMeasure4: '1/3 part ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 16:23:32',
    },
    {
      idDrink: '17215',
      strDrink: 'Spritz',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Ordinary Drink',
      strIBA: 'New Era Drinks',
      strAlcoholic: 'Alcoholic',
      strGlass: 'Old-Fashioned glass',
      strInstructions: 'Build into glass over ice, garnish and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'Über Eis in Glas einfüllen, garnieren und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Build into glass over ice, garnish and serve.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/j9evx11504373665.jpg',
      strIngredient1: 'Prosecco',
      strIngredient2: 'Campari',
      strIngredient3: 'Soda Water',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '6 cl',
      strMeasure2: '4 cl',
      strMeasure3: 'splash',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-02 18:34:25',
    },
  ],
};

export default mockDataFirstLetterS;
