const mealFirstLetterB = {
  meals: [
    {
      idMeal: '52767',
      strMeal: 'Bakewell tart',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: 'To make the pastry, measure the flour into a bowl and rub in the butter with your fingertips until the mixture resembles fine breadcrumbs. Add the water, mixing to form a soft dough.\r\nRoll out the dough on a lightly floured work surface and use to line a 20cm/8in flan tin. Leave in the fridge to chill for 30 minutes.\r\nPreheat the oven to 200C/400F/Gas 6 (180C fan).\r\nLine the pastry case with foil and fill with baking beans. Bake blind for about 15 minutes, then remove the beans and foil and cook for a further five minutes to dry out the base.\r\nFor the filing, spread the base of the flan generously with raspberry jam.\r\nMelt the butter in a pan, take off the heat and then stir in the sugar. Add ground almonds, egg and almond extract. Pour into the flan tin and sprinkle over the flaked almonds.\r\nBake for about 35 minutes. If the almonds seem to be browning too quickly, cover the tart loosely with foil to prevent them burning.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg',
      strTags: 'Tart,Baking,Alcoholic',
      strYoutube: 'https://www.youtube.com/watch?v=1ahpSTf_Pvk',
      strIngredient1: 'plain flour',
      strIngredient2: 'chilled butter',
      strIngredient3: 'cold water',
      strIngredient4: 'raspberry jam',
      strIngredient5: 'butter',
      strIngredient6: 'caster sugar',
      strIngredient7: 'ground almonds',
      strIngredient8: 'free-range egg, beaten',
      strIngredient9: 'almond extract',
      strIngredient10: 'flaked almonds',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '175g/6oz',
      strMeasure2: '75g/2½oz',
      strMeasure3: '2-3 tbsp',
      strMeasure4: '1 tbsp',
      strMeasure5: '125g/4½oz',
      strMeasure6: '125g/4½oz',
      strMeasure7: '125g/4½oz',
      strMeasure8: '1',
      strMeasure9: '½ tsp',
      strMeasure10: '50g/1¾oz',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52792',
      strMeal: 'Bread and Butter Pudding',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions: 'Grease a 1 litre/2 pint pie dish with butter.\r\nCut the crusts off the bread. Spread each slice with on one side with butter, then cut into triangles.\r\nArrange a layer of bread, buttered-side up, in the bottom of the dish, then add a layer of sultanas. Sprinkle with a little cinnamon, then repeat the layers of bread and sultanas, sprinkling with cinnamon, until you have used up all of the bread. Finish with a layer of bread, then set aside.\r\nGently warm the milk and cream in a pan over a low heat to scalding point. Don\'t let it boil.\r\nCrack the eggs into a bowl, add three quarters of the sugar and lightly whisk until pale.\r\nAdd the warm milk and cream mixture and stir well, then strain the custard into a bowl.\r\nPour the custard over the prepared bread layers and sprinkle with nutmeg and the remaining sugar and leave to stand for 30 minutes.\r\nPreheat the oven to 180C/355F/Gas 4.\r\nPlace the dish into the oven and bake for 30-40 minutes, or until the custard has set and the top is golden-brown.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xqwwpy1483908697.jpg',
      strTags: 'Pudding,Brunch',
      strYoutube: 'https://www.youtube.com/watch?v=Vz5W1-BmOE4',
      strIngredient1: 'butter',
      strIngredient2: 'bread',
      strIngredient3: 'sultanas',
      strIngredient4: 'cinnamon',
      strIngredient5: 'milk',
      strIngredient6: 'double cream',
      strIngredient7: 'eggs',
      strIngredient8: 'sugar',
      strIngredient9: 'nutmeg',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '25g/1oz',
      strMeasure2: '8 thin slices',
      strMeasure3: '50g/2oz',
      strMeasure4: '2 tsp',
      strMeasure5: '350ml/12fl',
      strMeasure6: '50ml/2fl oz',
      strMeasure7: '2 free-range',
      strMeasure8: '25g/1oz',
      strMeasure9: 'grated, to taste',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://cooking.nytimes.com/recipes/1018529-coq-au-vin',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export default mealFirstLetterB;
